engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
        #mass_threshold: 30
      - javascript
  eslint:
    enabled: true
ratings:
   paths:
   - app/**
   - lib/**
   - "**.rb"
   - "**.go"
exclude_paths:
- node_modules/**
- public/**
- test/**